use zoon::*;
use crate::tokens::*;
use crate::components::*;

pub fn button_examples() -> impl Element {
    Column::new()
        .s(Gap::new().y(SPACING_16))
        .item(h4("Buttons"))
        .item(small("Basic variants:"))
        .item(
            Row::new()
                .s(Gap::new().x(SPACING_12))
                .item(
                    button()
                        .label("Primary")
                        .variant(ButtonVariant::Primary)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .label("Secondary")
                        .variant(ButtonVariant::Secondary)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .label("Outline")
                        .variant(ButtonVariant::Outline)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .label("Ghost")
                        .variant(ButtonVariant::Ghost)
                        .on_press(|| {})
                        .build()
                )
        )
        .item(small("Additional variants:"))
        .item(
            Row::new()
                .s(Gap::new().x(SPACING_12))
                .item(
                    button()
                        .label("Link")
                        .variant(ButtonVariant::Link)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .label("Destructive")
                        .variant(ButtonVariant::Destructive)
                        .on_press(|| {})
                        .build()
                )
        )
        .item(small("Different sizes:"))
        .item(
            Row::new()
                .s(Gap::new().x(SPACING_12))
                .item(
                    button()
                        .label("Small")
                        .size(ButtonSize::Small)
                        .variant(ButtonVariant::Primary)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .label("Medium")
                        .size(ButtonSize::Medium)
                        .variant(ButtonVariant::Primary)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .label("Large")
                        .size(ButtonSize::Large)
                        .variant(ButtonVariant::Primary)
                        .on_press(|| {})
                        .build()
                )
        )
        .item(small("With icons:"))
        .item(
            Row::new()
                .s(Gap::new().x(SPACING_12))
                .item(
                    button()
                        .label("Save")
                        .left_icon("check")
                        .variant(ButtonVariant::Primary)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .label("Delete")
                        .left_icon("x")
                        .variant(ButtonVariant::Destructive)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .label("Next")
                        .right_icon("chevron-right")
                        .variant(ButtonVariant::Secondary)
                        .on_press(|| {})
                        .build()
                )
        )
        .item(small("Disabled buttons:"))
        .item(
            Row::new()
                .s(Gap::new().x(SPACING_12))
                .item(
                    button()
                        .label("Disabled Primary")
                        .variant(ButtonVariant::Primary)
                        .disabled(true)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .label("Disabled Secondary")
                        .variant(ButtonVariant::Secondary)
                        .disabled(true)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .label("Disabled Outline")
                        .variant(ButtonVariant::Outline)
                        .disabled(true)
                        .on_press(|| {})
                        .build()
                )
        )
        .item(small("Loading buttons:"))
        .item(
            Row::new()
                .s(Gap::new().x(SPACING_12))
                .item(
                    button()
                        .label("Loading...")
                        .variant(ButtonVariant::Primary)
                        .loading(true)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .label("Saving")
                        .left_icon("check")
                        .variant(ButtonVariant::Secondary)
                        .loading(true)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .variant(ButtonVariant::Ghost)
                        .loading(true)
                        .on_press(|| {})
                        .build()
                )
        )
        .item(small("Icon-only buttons:"))
        .item(
            Row::new()
                .s(Gap::new().x(SPACING_12))
                .item(
                    button()
                        .left_icon("search")
                        .variant(ButtonVariant::Ghost)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .left_icon("settings")
                        .variant(ButtonVariant::Outline)
                        .on_press(|| {})
                        .build()
                )
                .item(
                    button()
                        .left_icon("plus")
                        .variant(ButtonVariant::Primary)
                        .on_press(|| {})
                        .build()
                )
        )
}
