use zoon::*;
use crate::tokens::*;
use crate::components::*;

pub fn token_examples() -> impl Element {
    Column::new()
        .s(Gap::new().y(SPACING_16))
        .item(h4("Design Tokens"))
        .item(small("Color tokens:"))
        .item(
            Row::new()
                .s(Gap::new().x(SPACING_8))
                .item(
                    El::new()
                        .s(Width::exact(60))
                        .s(Height::exact(60))
                        .s(Background::new().color_signal(primary_6()))
                        .s(RoundedCorners::all(8))
                        .s(Align::center())
                        .child(
                            El::new()
                                .s(Font::new().color(white()).size(12))
                                .child(Text::new("Primary"))
                        )
                )
                .item(
                    El::new()
                        .s(Width::exact(60))
                        .s(Height::exact(60))
                        .s(Background::new().color_signal(neutral_7()))
                        .s(RoundedCorners::all(8))
                        .s(Align::center())
                        .child(
                            El::new()
                                .s(Font::new().color(white()).size(12))
                                .child(Text::new("Secondary"))
                        )
                )
                .item(
                    El::new()
                        .s(Width::exact(60))
                        .s(Height::exact(60))
                        .s(Background::new().color_signal(success_7()))
                        .s(RoundedCorners::all(8))
                        .s(Align::center())
                        .child(
                            El::new()
                                .s(Font::new().color(white()).size(12))
                                .child(Text::new("Success"))
                        )
                )
                .item(
                    El::new()
                        .s(Width::exact(60))
                        .s(Height::exact(60))
                        .s(Background::new().color_signal(primary_8()))
                        .s(RoundedCorners::all(8))
                        .s(Align::center())
                        .child(
                            El::new()
                                .s(Font::new().color(white()).size(12))
                                .child(Text::new("Warning"))
                        )
                )
                .item(
                    El::new()
                        .s(Width::exact(60))
                        .s(Height::exact(60))
                        .s(Background::new().color_signal(error_7()))
                        .s(RoundedCorners::all(8))
                        .s(Align::center())
                        .child(
                            El::new()
                                .s(Font::new().color(white()).size(12))
                                .child(Text::new("Error"))
                        )
                )
        )
        .item(small("Spacing tokens:"))
        .item(
            Row::new()
                .s(Gap::new().x(SPACING_8))
                .s(Align::new().center_y())
                .item(
                    El::new()
                        .s(Width::exact(SPACING_4))
                        .s(Height::exact(20))
                        .s(Background::new().color_signal(primary_6()))
                        .s(RoundedCorners::all(2))
                )
                .item(small("4px"))
                .item(
                    El::new()
                        .s(Width::exact(SPACING_8))
                        .s(Height::exact(20))
                        .s(Background::new().color_signal(primary_6()))
                        .s(RoundedCorners::all(2))
                )
                .item(small("8px"))
                .item(
                    El::new()
                        .s(Width::exact(SPACING_12))
                        .s(Height::exact(20))
                        .s(Background::new().color_signal(primary_6()))
                        .s(RoundedCorners::all(2))
                )
                .item(small("12px"))
                .item(
                    El::new()
                        .s(Width::exact(SPACING_16))
                        .s(Height::exact(20))
                        .s(Background::new().color_signal(primary_6()))
                        .s(RoundedCorners::all(2))
                )
                .item(small("16px"))
        )
        .item(small("Typography tokens:"))
        .item(
            Column::new()
                .s(Gap::new().y(SPACING_8))
                .item(h1("Heading 1"))
                .item(h2("Heading 2"))
                .item(h3("Heading 3"))
                .item(h4("Heading 4"))
                .item(h5("Heading 5"))
                .item(h6("Heading 6"))
                .item(paragraph("Body text paragraph"))
                .item(small("Small text"))
        )
        .item(small("Border radius tokens:"))
        .item(
            Row::new()
                .s(Gap::new().x(SPACING_12))
                .s(Align::new().center_y())
                .item(
                    El::new()
                        .s(Width::exact(40))
                        .s(Height::exact(40))
                        .s(Background::new().color_signal(primary_6()))
                        .s(RoundedCorners::all(2))
                )
                .item(
                    El::new()
                        .s(Width::exact(40))
                        .s(Height::exact(40))
                        .s(Background::new().color_signal(primary_6()))
                        .s(RoundedCorners::all(4))
                )
                .item(
                    El::new()
                        .s(Width::exact(40))
                        .s(Height::exact(40))
                        .s(Background::new().color_signal(primary_6()))
                        .s(RoundedCorners::all(8))
                )
                .item(
                    El::new()
                        .s(Width::exact(40))
                        .s(Height::exact(40))
                        .s(Background::new().color_signal(primary_6()))
                        .s(RoundedCorners::all(20))
                )
        )
}
